services:
  postgres:
    image: postgres:latest
    # Let Coolify create the volumes as needed
    volumes:
      - db_data_pg:/var/lib/postgresql/data
    environment:
      # Generate & store a random "DBNAME"
      - SERVICE_USER_DBNAME
      # Generate & store a random password
      - SERVICE_PASSWORD_PG

      # Instruct Postgres to use them
      - POSTGRES_DB=$SERVICE_USER_DBNAME
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_PG

    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
    environment:
      # Reuse the same random DB name & password
      - DB_NAME=${SERVICE_USER_DBNAME}
      - DB_PASSWORD=${SERVICE_PASSWORD_PG}
      - DB_HOST=postgres
      - DB_PORT=5432
      # ... other env variables as needed

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data_pg:
